# Project identification (copy for sast folder)
sonar.projectKey=cryptolabx-library-management
sonar.projectName=CryptoLabX Library Management
sonar.projectVersion=2.0

# Source directories to scan
sonar.sources=secure_application/src

# Language
sonar.language=py

# Source encoding
sonar.sourceEncoding=UTF-8

# SonarQube server URL
sonar.host.url=http://localhost:9000

# Authentication token
sonar.token=squ_ebf4966854d7f40544877daf333fabca182a810d

# Exclusions
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.git/**,sonarqube-25.6.0.109173/**
