sonar.projectKey=cryptolabx-analysis
sonar.projectName=CryptoLabX Analysis
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

# Change according to your language
sonar.python.version=3

sonar.host.url=http://localhost:9000
sonar.token=YOUR_SONAR_TOKEN
